import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import HeaderSection from '@/components/header/HeaderSection';
import FloatingComponent from '@/components/floating-components/FloatingComponent';
import CustomCursor from '@/components/CustomCursor';

const inter = localFont({
  src: './fonts/Inter/Inter-VariableFont_opsz,wght.ttf',
  variable: '--font-inter',
  display: 'swap'
});

const rightGrotesk = localFont({
  src: './fonts/right-grotesk/RightGrotesk-TightMedium.woff2',
  variable: '--font-inter',
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`scroll-smooth ${inter.variable} ${rightGrotesk.variable} antialiased`}>
        <HeaderSection />
        <CustomCursor />
        <main className='mt-[85px]'>{children}</main>
        {/* <FloatingComponent /> */}
      </body>
    </html>
  );
}
